CREATE TABLE IF NOT EXISTS quad_ss_poc_db.users (
    user_id INT(11) NOT NULL AUTO_INCREMENT,
    user_cd VARCHAR(15) DEFAULT NULL,
    first_name VARCHAR(45) DEFAULT NULL,
    last_name VARCHAR(45) DEFAULT NULL,
    email VARCHAR(60) DEFAULT NULL,
    phone_num VARCHAR(15) DEFAULT NULL,
    role VARCHAR(15) DEFAULT NULL,
    password VARCHAR(30) DEFAULT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id)
)  ENGINE=INNODB;
